"""Add new job columns

Revision ID: 62a8403a0bb0
Revises: 
Create Date: 2026-04-05 16:38:25.351739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a8403a0bb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('salary', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('job_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('closing_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ghosted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('ghosted')
        batch_op.drop_column('closing_date')
        batch_op.drop_column('location')
        batch_op.drop_column('job_url')
        batch_op.drop_column('salary')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('source')
        batch_op.drop_column('industry')

    # ### end Alembic commands ###
