"""add timestamp and notes to status history

Revision ID: 780653d1fa26
Revises: 62a8403a0bb0
Create Date: 2026-04-05 16:56:42.296006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780653d1fa26'
down_revision = '62a8403a0bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes_at_change', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_column('notes_at_change')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
